apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tomcat
  name: tomcat
  namespace: stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: service_tomcat
    spec:
      containers:
        - image: tomcat:8.5.69
          name: tomcat-service
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: netology-ml
  namespace: stage
spec:
  ports:
    - name: port8080
      port: 8080
      targetPort: 8080
  selector:
    app: service_tomcat
  type: NodePort
